Squashed 'mod/param/' changes from d6e1b7ac1..988e0e787
988e0e787 feat(param): add testcase

git-subtree-dir: mod/param
git-subtree-split: 988e0e787c0a396d2f48604b08efb64efca49cc5

diff --git a/.x-cmd/testcase/v0_test b/.x-cmd/testcase/v0_test
--- a/.x-cmd/testcase/v0_test
+++ b/.x-cmd/testcase/v0_test
@@ -2,9 +2,8 @@
 
 ___X_CMD_XRC_MODULE_IMPORTED=
 xrc param/latest
-xrc assert/latest
 
-# Section: define functions for param testcases
+# Section: define functions for param testcase
 
 param_type_unset    paramtest
 
@@ -45,7 +44,8 @@ A
 # Section: Testcase for generate advise json.
 
 test_advise_json(){
-    @assert stdout X_CMD_ADVISE_FUNC_NAME=paramtest paramtest _x_cmd_advise_json<<A
+  assert X_CMD_ADVISE_FUNC_NAME=paramtest
+  @assert stdout paramtest _x_cmd_advise_json<<A
 {
   "--candi_null": {
     "#1": [ "abc", "cde", "def" ],
@@ -166,64 +166,64 @@ A
 
 # Section: Testcase for other test.
 
-param_type    gitee     repo    "=~"   "[-A-Za-z0-9_]+"
+# param_type    gitee     repo    "=~"   "[-A-Za-z0-9_]+"
 
-gt_repo_info() {
-    param:scope     "gitee/$O"
-    param:dsl       '
-options:
-    #1|--dddd     "Provide repo"      <>:repo3 =~ [-A-Za-z0-9_]+
-'
-    param:run
+# gt_repo_info() {
+#     param:scope     "gitee/$O"
+#     param:dsl       '
+# options:
+#     #1|--dddd     "Provide repo"      <>:repo3 =~ [-A-Za-z0-9_]+
+# '
+#     param:run
 
-    echo "===== $1 ====="
-}
+#     echo "===== $1 ====="
+# }
 
-gt(){
-    param:dsl       '
-subcommand:
-    org                                     "manage org"
-'
-    param:run
-    if [ -z "${PARAM_SUBCMD}" ]; then
-        echo "Command Not Found. Show help." >&2
-        return 0
-    fi
-    gt_${PARAM_SUBCMD}  "$@"
-}
+# gt(){
+#     param:dsl       '
+# subcommand:
+#     org                                     "manage org"
+# '
+#     param:run
+#     if [ -z "${PARAM_SUBCMD}" ]; then
+#         echo "Command Not Found. Show help." >&2
+#         return 0
+#     fi
+#     gt_${PARAM_SUBCMD}  "$@"
+# }
 
-gt_org(){
-    param:scope     "gitee/$O"
-    param:dsl       '
-subcommands:
-    repo                    "List all repos"
-'
-    param:run
-    echo "$1 ++++++++++ $PARAM_SUBCMD"
-    if [ -z "$PARAM_SUBCMD" ]; then
-        gt_log error "Command Not Found. Show help."
-        return 0
-    fi
+# gt_org(){
+#     param:scope     "gitee/$O"
+#     param:dsl       '
+# subcommands:
+#     repo                    "List all repos"
+# '
+#     param:run
+#     echo "$1 ++++++++++ $PARAM_SUBCMD"
+#     if [ -z "$PARAM_SUBCMD" ]; then
+#         gt_log error "Command Not Found. Show help."
+#         return 0
+#     fi
 
-    "gt_org_${PARAM_SUBCMD}" "$@"
-}
+#     "gt_org_${PARAM_SUBCMD}" "$@"
+# }
 
 # FIXME: We should ask some questions to get the $1
 # gt_repo_info
 
 # EndSection
 
-# Section: Run all testcases.
+# Section: Run all testcase.
 
-start_test() {
-    < "$1" awk '$0~/^test_[^\(]+\(\)/{ gsub(/\(\)\{/, "", $0); print $0 }' | while read -r line; do
-        echo "Testing Function: $line"
-        if ! eval "$line"; then
-            printf "\033[0;31m======= Fail at function: %s \033[0m" "$line" >&2
-            break
-        fi
-    done
-}
+# start_test() {
+#     < "$1" awk '$0~/^test_[^\(]+\(\)/{ gsub(/\(\)\{/, "", $0); print $0 }' | while read -r line; do
+#         echo "Testing Function: $line"
+#         if ! eval "$line"; then
+#             printf "\033[0;31m======= Fail at function: %s \033[0m" "$line" >&2
+#             break
+#         fi
+#     done
+# }
 
 # FIXME: All char was merge when in regex ui.
 # FIXME: The color was no close
@@ -232,12 +232,13 @@ start_test() {
 # Example:
 # #start_test ./testcase/v0_test_option  ls_option ls_subcmd ls_option_subcmd
 
-for testcase in option namelist subcmd param_default quote dryrun ls_subcmd ls_option ls_option_subcmd  help license; do
-    . "$(x wsroot)/.x-cmd/testcases/v0_test_$testcase"
-    start_test "$(x wsroot)/.x-cmd/testcases/v0_test_$testcase"
-done
+# for testcase in option namelist subcmd param_default quote dryrun ls_subcmd ls_option ls_option_subcmd  help license; do
+#     # . "$(x wsroot)/.x-cmd/testcase/v0_test_$testcase"
+#     # start_test "$(x wsroot)/.x-cmd/testcase/v0_test_$testcase"
+#   @assert:file:func "$(x wsroot)/.x-cmd/testcase/v0_test_$testcase"
+# done
 
-. "$(x wsroot)/.x-cmd/testcases/v0_test_ui"
-start_test "$(x wsroot)/.x-cmd/testcases/v0_test"
-
+# . "$(x wsroot)/.x-cmd/testcase/v0_test_ui"
+# start_test "$(x wsroot)/.x-cmd/testcase/v0_test"
 # EndSection
+@assert:file:func
