...

diff --git a/mod/gl/lib/groups/main b/mod/gl/lib/groups/main
--- a/mod/gl/lib/groups/main
+++ b/mod/gl/lib/groups/main
@@ -2,7 +2,7 @@
 # shellcheck disable=SC2039,3043
 
 # define lazy loader
-# ___x_cmd_definelazyloader   ___x_cmd_gl_groups_member           gitlab/lib/groups/member
+# ___x_cmd_definelazyloader   ___x_cmd_gl_groups_member           gl/lib/groups/member
 
 ___x_cmd_gl_groups(){
     param:scope     ___x_cmd_gl
@@ -18,7 +18,7 @@ ___x_cmd_gl_groups(){
     param:run
 
     ___x_cmd_gl_groups _param_help_doc
-    gitlab_log warn "Subcmd Not Found."
+    gl_log warn "Subcmd Not Found."
     return 1
 }
 
@@ -31,7 +31,7 @@ ___x_cmd_gl_subgroup(){
     param:run
 
     ___x_cmd_gl_subgroup _param_help_doc
-    gitlab_log warn "Subcmd Not Found."
+    gl_log warn "Subcmd Not Found."
     return 1
 }
 
@@ -60,7 +60,7 @@ options:
 '
     param:run
 
-    ___gitlab_ui_mutual ___x_cmd_gl_get_multi "/groups" per_page  page <<A
+    ___gl_ui_mutual ___x_cmd_gl_get_multi "/groups" per_page  page <<A
         ___ui_table_json Id=.id Name=.name Path=.path Visibility=.visibility Url=.web_url -- \$@
 A
 }
@@ -86,7 +86,7 @@ options:
 '
     param:run
 
-    ___gitlab_ui_mutual ___x_cmd_gl_get_multi "/groups/$1/subgroups" <<A
+    ___gl_ui_mutual ___x_cmd_gl_get_multi "/groups/$1/subgroups" <<A
         ___ui_table_json Id=.id Name=.name Path=.path Visibility=.visibility Url=.web_url -- \$@
 A
 }
@@ -117,7 +117,7 @@ options:
 
 # Section: create
 # shellcheck disable=SC2181
-# TODO:On GitLab SaaS, you must use the GitLab UI to create groups without a parent group. You cannot use the API to do this.???
+# TODO:On gl SaaS, you must use the gl UI to create groups without a parent group. You cannot use the API to do this.???
 ___x_cmd_gl_groups_create(){
     param:scope     ___x_cmd_gl
     param:dsl       '
@@ -131,13 +131,13 @@ options:
     param:run
     local name
     name="$1"
-    [ $# -ne 0 ] || { gitlab_log error "Please provide groups name"; return 1; }
-    local gitlab_path="$name"
-    [ -z "$p" ] || gitlab_path="$p"
-    local gen_gitlab_json
-    gen_gitlab_json="$(param:option2json -p +name path=gitlab_path)"
+    [ $# -ne 0 ] || { gl_log error "Please provide groups name"; return 1; }
+    local gl_path="$name"
+    [ -z "$p" ] || gl_path="$p"
+    local gen_gl_json
+    gen_gl_json="$(param:option2json -p +name path=gl_path)"
 
-    ___x_cmd_gl_http post "/groups" "$gen_gitlab_json" | \
+    ___x_cmd_gl_http post "/groups" "$gen_gl_json" | \
     {
         ___x_cmd_git_json_query_rename id=.id
         if [ -n "$id" ]; then
@@ -152,7 +152,7 @@ options:
 
 # Section: create subgroup
 # shellcheck disable=SC2181
-# TODO:On GitLab SaaS, you must use the GitLab UI to create groups without a parent group. You cannot use the API to do this.???
+# TODO:On gl SaaS, you must use the gl UI to create groups without a parent group. You cannot use the API to do this.???
 ___x_cmd_gl_subgroup_create(){
     param:scope     ___x_cmd_gl
     param:dsl       '
@@ -164,8 +164,8 @@ options:
     param:run
     local group_path="$subgroup_path"
     [ -n "$group_path" ] || group_path="$name"
-    gen_gitlab_json="$(param:option2json -subgroup_path path=group_path)"
-    ___x_cmd_gl_http post "/groups" "$gen_gitlab_json"| \
+    gen_gl_json="$(param:option2json -subgroup_path path=group_path)"
+    ___x_cmd_gl_http post "/groups" "$gen_gl_json"| \
     {
         ___x_cmd_git_json_query_rename id=.id
         if [ -n "$id" ]; then
@@ -191,13 +191,13 @@ options:
     #1                          "The ID of the group."
 '
     param:run
-    [ $# -ne 0 ] || { gitlab_log error "Please provide groups ID"; return 1; }
-    local gitlab_path="$p"
-    local gen_gitlab_json
-    # path=gitlab_path
-    gen_gitlab_json="$(param:option2json -p path=gitlab_path)"
+    [ $# -ne 0 ] || { gl_log error "Please provide groups ID"; return 1; }
+    local gl_path="$p"
+    local gen_gl_json
+    # path=gl_path
+    gen_gl_json="$(param:option2json -p path=gl_path)"
 
-    ___x_cmd_gl_http put "/groups/$1" "$gen_gitlab_json" | \
+    ___x_cmd_gl_http put "/groups/$1" "$gen_gl_json" | \
     {
         ___x_cmd_git_json_query_rename id=.id
         if [ -n "$id" ]; then
@@ -219,7 +219,7 @@ ___x_cmd_gl_groups_repo(){
     param:run
 
     ___x_cmd_gl_groups_repo _param_help_doc
-    gitlab_log warn "Subcmd Not Found."
+    gl_log warn "Subcmd Not Found."
     return 1
 }
 
@@ -235,7 +235,7 @@ options:
 '
     param:run
 
-    ___gitlab_ui_mutual ___x_cmd_gl_get_multi "/groups/$id/projects" page per_page visibility archived <<A
+    ___gl_ui_mutual ___x_cmd_gl_get_multi "/groups/$id/projects" page per_page visibility archived <<A
         ___ui_table_json Id=.id Name=.name path=.path visibility=.visibility web_url=.web_url -- \$@
 A
 }
@@ -280,7 +280,7 @@ options:
 '
  param:run
 
-  ___gitlab_ui_mutual  ___x_cmd_gl_get_multi  "/groups/$id/issues" sort order_by search state  <<A
+  ___gl_ui_mutual  ___x_cmd_gl_get_multi  "/groups/$id/issues" sort order_by search state  <<A
         ___ui_table_json Id=.id iid=.iid project_id=.project_id title=.title state=.state web_url=.web_url -- \$@
 A
 }
diff --git a/mod/gl/lib/utils b/mod/gl/lib/utils
--- a/mod/gl/lib/utils
+++ b/mod/gl/lib/utils
@@ -5,12 +5,12 @@
 # Section 2: Wrapping std/http module with object naming changing
 ############################
 ___x_cmd_gl_resp_header(){
-    O="${O:-___X_BASH_HTTP____x_cmd_gl_GITLAB_DEFAULT}" ___x_cmd_http_resp header "$@"
+    O="${O:-___X_BASH_HTTP____x_cmd_gl_GL_DEFAULT}" ___x_cmd_http_resp header "$@"
 }
 
 # TODO: Not supported yet
 ___x_cmd_gl_resp_body(){
-    O="${O:-___X_BASH_HTTP____x_cmd_gl_GITLAB_DEFAULT}" ___x_cmd_http_resp body "$@"
+    O="${O:-___X_BASH_HTTP____x_cmd_gl_GL_DEFAULT}" ___x_cmd_http_resp body "$@"
 }
 
 ___x_cmd_gl_get_multi() {
@@ -51,10 +51,10 @@ _____x_cmd_gl_next_url(){
 }
 
 ___x_cmd_gl_http(){
-    if ! O="${O:-___x_cmd_gl_GITLAB_DEFAULT}" ___x_cmd_http header get Content-Type 1>/dev/null 2>&1; then
-         O="${O:-___x_cmd_gl_GITLAB_DEFAULT}" ___x_cmd_http header put Content-Type application/json
+    if ! O="${O:-___x_cmd_gl_GL_DEFAULT}" ___x_cmd_http header get Content-Type 1>/dev/null 2>&1; then
+         O="${O:-___x_cmd_gl_GL_DEFAULT}" ___x_cmd_http header put Content-Type application/json
     fi
-    O="${O:-___x_cmd_gl_GITLAB_DEFAULT}" ___x_cmd_http "$@"
+    O="${O:-___x_cmd_gl_GL_DEFAULT}" ___x_cmd_http "$@"
 }
 
 ############################
@@ -78,10 +78,10 @@ ___x_cmd_gl_param_normalize_repo(){
         ;;
     *)
         ___x_cmd_gl_current_owner 1>/dev/null
-        if [ -z "$___x_cmd_gl_DEFAULT_OWNER" ]; then
+        if [ -z "$___X_CMD_GL_DEFAULT_OWNER" ]; then
             printf "No owner provided. Default owner not set.\n" >&2
         fi
-        owner_project="$(printf "%s" "$___x_cmd_gl_DEFAULT_OWNER/$op")"
+        owner_project="$(printf "%s" "$___X_CMD_GL_DEFAULT_OWNER/$op")"
         ;;
     esac
     printf "%s" "$owner_project" | sed s:'/':'%2F':g
@@ -90,7 +90,7 @@ ___x_cmd_gl_param_normalize_repo(){
 ### Repo #1
 
 ___x_cmd_gl_parse_owner_repo(){
-    local O="${O:-___x_cmd_gl_GITLAB_DEFAULT}"
+    local O="${O:-___x_cmd_gl_GL_DEFAULT}"
     if [ -z "$repo" ]; then
         repo="$(___x_cmd_gl_current_repo)"
     fi
@@ -116,7 +116,7 @@ _____x_cmd_git_repo(){
     repo="${repo%.*}"
     printf "%s" "$repo"
 }
-___gitlab_ui_mutual(){
+___gl_ui_mutual(){
     if [ ! -t 1 ] || [ -n "$ENFORCE_JSON" ] ; then
         "$@"
     else
@@ -124,7 +124,7 @@ ___gitlab_ui_mutual(){
         eval "$(cat)"
     fi
 
-    local ___gitlab_exit_code="$?"
-    [ "$___gitlab_exit_code" -eq 0 ] || gitlab_log error "${___gitlab_error_msg:-"Couldn't find any data"}"
-    return "$___gitlab_exit_code"
+    local ___gl_exit_code="$?"
+    [ "$___gl_exit_code" -eq 0 ] || gl_log error "${___gl_error_msg:-"Couldn't find any data"}"
+    return "$___gl_exit_code"
 }
