...

diff --git a/mod/ffmpeg/latest b/mod/ffmpeg/latest
--- a/mod/ffmpeg/latest
+++ b/mod/ffmpeg/latest
@@ -1,32 +1,37 @@
-# Author:       Li Junhao   l@x-cmd.com     # xrc
-# shellcheck    shell=sh    disable=SC3043
+# Author:       Li Junhao       l@x-cmd.com                 # xrc
+# shellcheck    shell=sh        disable=SC2039,3043
 
-___x_cmd_qr(){
-    local op="${1}";
+___x_cmd_ffmpeg(){
+    local op="$1"
 
     case "$op" in
-        enc)    shift 1; ___x_cmd_qr_enc "$@" ;;
-        dec)    shift 1; ___x_cmd_qr_dec "$@" ;;
-        *://*)  ___x_cmd_qr_enc_default "$op" ;;
-        "")     # decode from file, like
+        show)       shift; ___x_cmd_ffmpeg_show "$@" ;;
+        convert)    shift; ___x_cmd_ffmpeg_convert "$@" ;;
+        play)       shift; ___x_cmd_ffmpeg_play "$@" ;;
+        *)          shift; ___x_cmd_ffmpeg_origin "$@" ;;
     esac
+
 }
 
-___x_cmd_qr_enc(){
-    ___x_cmd_static_build_file qrencode qrencode "$@"
-}
-
-___x_cmd_qr_enc_default(){
-    : Provide param
-    ___x_cmd_static_build_file qrencode qrencode -t utf8i "${1:?Provide URL}"
-}
-
-___x_cmd_qr_dec(){
-    if [ -t 0 ]; then
-        : qr decode from input stream
-    else
-        : qr decode file, output url
+___x_cmd_ffmpeg_origin(){
+    if ! ___x_cmd_pkg_xbin_init ffmpeg ___x_cmd_ffmpeg_origin; then
+        x:error "Fail to pkg_xbin_init ffmpeg"
+        return 1
     fi
+    ___x_cmd_ffmpeg_origin "$@"
 }
 
-xrc setmain ___x_cmd_qr
+___x_cmd_ffmpeg_show(){
+    local op
+    op="$1"
+
+    case "$op" in
+        buildconf)      ___x_cmd_ffmpeg_origin -buildconf ;;
+        formats)        ___x_cmd_ffmpeg_origin -formats ;;
+    esac
+
+}
+
+# EndSection
+
+xrc setmain ___x_cmd_ffmpeg
diff --git a/mod/gh/latest b/mod/gh/latest
--- a/mod/gh/latest
+++ b/mod/gh/latest
@@ -1,32 +1,74 @@
-# Author:       Li Junhao   l@x-cmd.com     # xrc
-# shellcheck    shell=sh    disable=SC3043
+# shellcheck shell=sh                   # xrc
+# shellcheck disable=SC2039,3043
 
-___x_cmd_qr(){
-    local op="${1}";
+# author:       Li Junhao           l@x-cmd.com
 
-    case "$op" in
-        enc)    shift 1; ___x_cmd_qr_enc "$@" ;;
-        dec)    shift 1; ___x_cmd_qr_dec "$@" ;;
-        *://*)  ___x_cmd_qr_enc_default "$op" ;;
-        "")     # decode from file, like
-    esac
+xrc http param str ui
+xrc ui/lib/table
+
+xrc:inner:lib gh utils resource config token repo/main repo/branch/main current user/main org/main \
+    repo/member/main repo/pr/main _type/main org/member org/repo repo/release/main action/workflows \
+    action/run action/job
+
+x log init gh
+
+___x_cmd_gh(){
+    param:subcmd ___x_cmd_gh                    \
+        repo          "repo command"            \
+        current       "set current owner, repo" \
+        org           "manage org"              \
+        user          "user"                    \
+        config        "save, load, which"       \
+        token         "set token"               \
+        auth          "Authorize gh"
+    param:subcmd:try
+
+    # param:subcmd ___x_cmd_gh_repo               \
+    #     release       "manage release"          \
+    #     member        "Authorize gh"
+    # param:subcmd:try
+    param:run
+
+    gh_log warn "Subcmd Not Found."
+    ___x_cmd_gh _param_help_doc
+    return 1
 }
 
-___x_cmd_qr_enc(){
-    ___x_cmd_static_build_file qrencode qrencode "$@"
-}
 
-___x_cmd_qr_enc_default(){
-    : Provide param
-    ___x_cmd_static_build_file qrencode qrencode -t utf8i "${1:?Provide URL}"
-}
+############################
+# Section 10: Instantiation
+############################
 
-___x_cmd_qr_dec(){
-    if [ -t 0 ]; then
-        : qr decode from input stream
-    else
-        : qr decode file, output url
+____x_cmd_gh_make() {
+    param:void
+    local O_ORIGINAL=${1:?Provide client name by O environment}
+    local O="___x_cmd_gh_$O_ORIGINAL"
+
+    http make  'https://api.github.com'
+    http header put Accept "application/vnd.github.v3+json"
+
+    local token
+    token="$(O="$O_ORIGINAL" ___x_cmd_gh_config_get "oauth_token")"
+
+    if [ -n "$token" ]; then
+        O="___x_cmd_gh_$O_ORIGINAL" http header put Authorization "token $token"
+        local user
+        user="$(O="$O_ORIGINAL" ___x_cmd_gh_current_owner)" || return 1
+        gh_log info "Hi $user! You've successfully authenticated."
+        return 0
     fi
+
+    local info
+    info=$(printf "\n%s %s \n%s" \
+         "$(ui yellow 'You need run command to add token:')" \
+         "$(ui bold cyan "\`gh token <token>\`")" \
+         "$(ui 'https://github.com/settings/tokens')")
+    gh_log warn "Token is null.${info}"
 }
 
-xrc setmain ___x_cmd_qr
+if [ -z "$DO_NOT_INIT_GITHUB_DEFAULT" ]; then
+    ____x_cmd_gh_make "GITHUB_DEFAULT" && DO_NOT_INIT_GITHUB_DEFAULT="true"
+fi
+
+
+xrc setmain ___x_cmd_gh
diff --git a/mod/gt/latest b/mod/gt/latest
--- a/mod/gt/latest
+++ b/mod/gt/latest
@@ -1,32 +1,77 @@
-# Author:       Li Junhao   l@x-cmd.com     # xrc
-# shellcheck    shell=sh    disable=SC3043
+# shellcheck shell=sh
+# shellcheck disable=SC2039,3043
 
-___x_cmd_qr(){
-    local op="${1}";
+# author:       Li Junhao           edwin.jh.lee@gmail.com    edwinjhlee.github.io
+# maintainer:   Li Junhao
 
-    case "$op" in
-        enc)    shift 1; ___x_cmd_qr_enc "$@" ;;
-        dec)    shift 1; ___x_cmd_qr_dec "$@" ;;
-        *://*)  ___x_cmd_qr_enc_default "$op" ;;
-        "")     # decode from file, like
-    esac
+# loading dependencies
+xrc http param str ui
+xrc ui/lib/table gh/lib/resource
+
+xrc:inner:lib gt utils config token user current issue enterprise/main enterprise/member enterprise/team org/main org/member \
+    repo/utils repo/main repo/pr/main repo/pr/assign repo/pr/tester repo/release/main repo/release/attachment repo/member repo/tag repo/page repo/branch _type/main
+
+
+x log init gt
+___x_cmd_gt(){
+    param:subcmd ___x_cmd_gt                                        \
+        repo                             "repo command"             \
+        issue                            "issue"                    \
+        current                          "set current owner, repo"  \
+        enterprise                       "manage enterprise"        \
+        org                              "manage org"               \
+        user                             "user"                     \
+        config                           "save, load, which"        \
+        token                            "set token"
+    param:subcmd:try
+
+    param:subcmd ___x_cmd_gt_repo                                        \
+        pr                               "pull request"             \
+        release                          "release management"       \
+        member                           "repo member"              \
+        tag                              "repo tag"
+    param:subcmd:try
+    param:run
+
+    gt_log warn "Subcmd Not Found."
+    ___x_cmd_gt _param_help_doc
+    return 1
 }
 
-___x_cmd_qr_enc(){
-    ___x_cmd_static_build_file qrencode qrencode "$@"
-}
 
-___x_cmd_qr_enc_default(){
-    : Provide param
-    ___x_cmd_static_build_file qrencode qrencode -t utf8i "${1:?Provide URL}"
-}
+############################
+# Section 10: Instantiation
+############################
+___x_cmd_gt_make(){
+    param:void
 
-___x_cmd_qr_dec(){
-    if [ -t 0 ]; then
-        : qr decode from input stream
-    else
-        : qr decode file, output url
+    local O_ORIGINAL="${1:?Provide client name by O environment}"
+    local O="___x_cmd_gt_$O_ORIGINAL"
+
+    http make  'https://gitee.com/api'
+    http header put type  "application/json;charset=utf-8"
+
+    local token
+    token="$(O="$O_ORIGINAL" ___x_cmd_gt_config_get "oauth_token")"
+
+    if [ -n "$token" ]; then
+        O="___x_cmd_gt_$O_ORIGINAL" http header put Authorization "token $token"
+        O="$O_ORIGINAL" ___x_cmd_gt_current_owner 1>/dev/null || return 1
+        gt_log info "Hi $___X_CMD_GITEE_DEFAULT_OWNER! You've successfully authenticated."
+        return 0
     fi
+
+    local info
+    info=$(printf "\n%s %s \n%s" \
+         "$(ui yellow 'You need run command to add token:')" \
+         "$(ui bold cyan "\`gt token <token>\`")" \
+         "$(ui 'https://gitee.com/profile/personal_access_tokens')")
+    gt_log warn "Token is null.${info}"
 }
 
-xrc setmain ___x_cmd_qr
+if [ -z "$DO_NOT_INIT_GITEE_DEFAULT" ]; then
+    ___x_cmd_gt_make "GITEE_DEFAULT" && DO_NOT_INIT_GITEE_DEFAULT="true"
+fi
+
+xrc setmain ___x_cmd_gt
+
