Squashed 'mod/gt/' changes from 4ddb4aa8a..544e59302
544e59302 chore(table): add -t 1 to output origin json
72b331d50 feat(team): init enterprise team management
002d0438b style: update code format
f019333df style(owner): remove owner options and add repo description
440f1ded1 feat(branch): add branch protection management
a82a17608 style(gt): update code formart
985c92fea style(gt): update code format
8b0904a06 feat(branch): add repo branch manage
e65c16f71 fix(repo): remove for in repo update
54f498d60 feat(repo): add repo update feature
a724fc4a6 chore: update types config
ad42ec424 feat(page): add page and per_page  param option
507f9386a feat(owner): add owner param option
2b6338ca7 style(org-enterprise): update code style format
70dc4e9a2 style(gt): update repo code format style
c72301bd1 ...
44d615611 feat(repo): update repo code format
20dc71d35 update path
80fd14476 ...
00ec648ab update
f06729135 style: update code format style
307068507 style: add local prevent global variable
b7431e4b6 fix: fix for in return code
7ea5088cb update local
d9fa04c14 org member
de18600f1 org main
0aeab4e66 enterprises member update
8bbbbcaac enterprise main
cf9c147cc feat(pr,tag,release): import ui style to output
b26ae58fb feat(token): add token replace feature
ec9d630b3 style: update types UpperCase
4db1e69d3 feat(issue): done issue import ui
ec03b8b52 feat(config): update config setup of yml awk
c48eb00b6 feat(command): add command printf log to repo repo_member
205682841 feat(select): replace select to form for confirm del and clear repo
3631dc776 feat(token): add token replace
418d48ce9 update http make

git-subtree-dir: mod/gt
git-subtree-split: 544e59302fb6d21b97b772669024209d0423a22c

diff --git a/lib/issue b/lib/issue
--- a/lib/issue
+++ b/lib/issue
@@ -26,92 +26,138 @@ subcmd:
 }
 
 
+# shellcheck disable=SC2154
 ___x_cmd_gt_issue_create() {
     param:scope     "gitee/$O"
     param:dsl      '
 options:
-    --owner         "owner"                         <>
-    --title         "title"                         <>
-    --body          "issue describe"                <>=""
-    --repo          "repo path"                     <>
-    --type          "issue type"                    <>=""
-    --assignee      "assignee space address"        <>=""
-    --collaborators "collaborators space address"   <>=""
-    --milestone     "milestone serial number"       <>=""
-    --labels        "labels"                        <>=""
-    --program       "project ID"                    <>=""
+    --title         "title"                                                              <>
+    --repo          "Provide owner name and repo name.(default:the current user repo)"   <>:RepoName
+    --body          "issue describe"                                                     <>=""
+    --type          "issue type"                                                         <>=""
+    --assignee      "assignee space address"                                             <>=""
+    --collaborators "collaborators space address"                                        <>=""
+    --milestone     "milestone serial number"                                            <>=""
+    --labels        "labels"                                                             <>=""
+    --program       "project ID"                                                         <>=""
     --security      "is it private"
 '
     security=${security:-false}
     param:run
-    ______x_cmd_gt_post_json "/v5/repos/${owner##*/}/issues" repo=$repo title issue_type=$type body assignee \
-        collaborators milestone labels program security_hole=$security
+
+    local data
+    local id
+    local title
+    local html_url
+    data="$(______x_cmd_gt_post_json "/v5/repos/${owner##*/}/issues" repo="$repo" title issue_type="$type" body assignee \
+        collaborators milestone labels program security_hole="$security" || return 1)"
+    ___x_cmd_gt_json_query_rename "$data" id=.number title=.title html_url=.html_url
+    [ -n "$id" ] && ___x_cmd_ui tf "true" "Success" "id: $id" "title: $title" "url: $html_url" && return 0
+                    gt_log        "error" "Create issue failure"                               && return 1
 }
 
+# shellcheck disable=SC2154
 ___x_cmd_gt_issue_update() {
     param:scope     "gitee/$O"
     param:dsl       '
+type:
+    State = open progressing closed
 options:
-    --owner         "owner"                         <>
-    --number        "issue number"                  <>
-    --repo          "repo path"                     <>=""
-    --title         "title"                         <>=""
-    --state         "issue state"                   <>=""
-    --body          "issue describe"                <>=""
-    --assignee      "assignee space address"        <>=""
-    --collaborators "collaborators space address"   <>=""
-    --milestone     "milestone serial number"       <>=""
-    --labels        "labels"                        <>=""
-    --program       "project ID"                    <>=""
+    --repo          "Provide owner name and repo name.(default:the current user repo)"   <>:RepoName
+    --number        "issue number"                                                       <>
+    --title         "title"                                                              <>=""
+    --state         "issue state "                                                       <>:State
+    --body          "issue describe"                                                     <>=""
+    --assignee      "assignee space address"                                             <>=""
+    --collaborators "collaborators space address"                                        <>=""
+    --milestone     "milestone serial number"                                            <>=""
+    --labels        "labels"                                                             <>=""
+    --program       "project ID"                                                         <>=""
     --security      "is it private"
 '
     param:run
     security=${security:-false}
-    ______x_cmd_gt_patch_json "/v5/repos/${owner##*/}/issues/${number}" repo title state body assignee \
-        collaborators milestone labels program security_hole=$security
+
+    local data
+    local id
+    local state
+    local html_url
+    data="$(______x_cmd_gt_patch_json "/v5/repos/${owner##*/}/issues/${number}" repo title state body assignee \
+        collaborators milestone labels program security_hole="$security" || return 1)"
+    ___x_cmd_gt_json_query_rename "$data" id=.number state=.state html_url=.html_url
+    [ -n "$id" ] && ___x_cmd_ui tf "true" "Success" "id: $id" "state: $state" "url: $html_url" && return 0
+                    gt_log        "error" "Update issue failure"                               && return 1
 }
 
+# shellcheck disable=SC2154
 ___x_cmd_gt_issue_logs(){
     param:scope     "gitee/$O"
     param:dsl       '
 options:
-    --owner         "owner"                 <>
-    --repo          "repo path"             <>
-    --number        "issue number"          <>
-    --sort          "sort(asc、desc)"       <>="desc"
+    --repo          "Provide owner name and repo name.(default:the current user repo)"   <>:RepoName
+    --number        "issue number"                                                       <>
+    --sort          "sort(asc、desc)"                                                    <>="desc"
 '
     param:run
-    ______x_cmd_gt_get "/v5/repos/${owner##*/}/issues/${number}/operate_logs" repo sort
+    ___x_cmd_gt_param_init_owner_repo
+
+    if [ -t 1 ]; then
+        if ___ui_table_json Time=.created_at User=.user.login Type=.action_type Content=.content \
+            -- "______x_cmd_gt_get" "/v5/repos/${owner_repo##*/}/issues/${number}/operate_logs" repo sort; then
+            return 0
+        fi
+    else
+        ______x_cmd_gt_get "/v5/repos/${owner_repo##*/}/issues/${number}/operate_logs" repo sort && \
+            return 0
+    fi
+    gt_log error "Couldn't find any data by: $repo $number"
+    return 1
 }
 
 # shellcheck shell=sh
 # shellcheck disable=SC2039,3043,SC2154
 
-# schedule、deadline、created_at、finished_at 用UI来处理
 ___x_cmd_gt_repo_issue() {
     param:scope     "gitee/$O"
     param:dsl       '
 type:
-    state = open progressing closed rejected all
+    State = open progressing closed rejected all
 options:
-    --repo          "Repo name"                 <>
-    --state         "issue state"               <>:state=all
-    --labels        "labels"                    <>=""
-    --milestone     "milestone"                 <>=""
-    --assignee      "assignee"                  <>=""
-    --creator       "creator"                   <>=""
-    --program       "program"                   <>=""
-    --sort          "sort"                      <>="created"
-    --direction     "direction"                 <>="desc"
-    --number        "repo issue number"         <>=""
+    --repo          "Provide owner name and repo name.(default:the current user repo)"   <>:RepoName
+    --state         "issue state"                                                        <>:State=all
+    --labels        "labels"                                                             <>=""
+    --labels        "labels"                                                             <>=""
+    --milestone     "milestone"                                                          <>=""
+    --assignee      "assignee"                                                           <>=""
+    --creator       "creator"                                                            <>=""
+    --program       "program"                                                            <>=""
+    --page          "page"                                                               <>:number=1
+    --per_page      "per_page"                                                           <>:number=20
+    --sort          "sort"                                                               <>="created"
+    --direction     "direction"                                                          <>="desc"
+    --number        "repo issue number"                                                  <>=""
 '
     param:run
     ___x_cmd_gt_param_init_owner_repo
-    if [ -z $number ]; then
-        ___ui_table_json "$(printf "%s" "______x_cmd_gt_get_multi \"/v5/repos/${owner_repo}/issues\" state labels sort direction|| return 1" )" \
-            IssueNumber=.number Title=.title State=.issue_state Assigner=.assignee.name body=.body && return 0
+
+    if [ -z "$number" ]; then
+        if [ -t 1 ]; then
+            if ___ui_table_json IssueNumber=.number Title=.title State=.issue_state Assigner=.assignee.name Body=.body \
+                -- "______x_cmd_gt_get_multi" "/v5/repos/${owner_repo}/issues" state labels sort direction page per_page; then
+                return 0
+            fi
+        else
+            ______x_cmd_gt_get_multi "/v5/repos/${owner_repo}/issues" state labels sort direction page per_page && \
+                return 0
+        fi
+        gt_log error "Couldn't find any data by: ${owner_repo}"
+        return 1
     else
         local data
+        local id
+        local title
+        local state
+        local assignee
         data="$(______x_cmd_gt_get "/v5/repos/${owner_repo}/issues/${number}")"
         ___x_cmd_gt_json_query_rename "$data" id=.number title=.title state=.state assignee=.assignee.name
         if [ -n "$id" ];then
@@ -130,19 +176,32 @@ ___x_cmd_gt_org_issue(){
     param:scope     "gitee/$O"
     param:dsl       '
 options:
+    --org           "organization path"                            <>
     --filter        "filter(assigned,created,all)"                 <>="assigned"
     --state         "state(open,progerssing,closed,rejected)"      <>="open"
     --labels        "labels"                                       <>=""
     --sort          "sort(created,updated)"                        <>="created"
     --direction     "direction(asc、desc)"                         <>="desc"
-    --org           "organization path"                            <>
+    --page          "page"                                         <>:number=1
+    --per_page      "per_page"                                     <>:number=20
 '
     param:run
 
-    ___ui_table_json "$(printf "%s" "______x_cmd_gt_get_multi \"/v5/orgs/${org##*/}/issues\" filter state labels sort direction since page per_page || return 1" )" \
-        IssueNumber=.number State=.issue_state Assigner=.assignee.name Repository=.repository.full_name Type=.issue_type Title=.title Url=.html_url && return 0
+    if [ -t 1 ]; then
+        if ___ui_table_json IssueNumber=.number State=.issue_state Assigner=.assignee.name Repository=.repository.full_name Type=.issue_type Title=.title Url=.html_url \
+            -- "______x_cmd_gt_get_multi" "/v5/orgs/${org##*/}/issues" filter state labels sort direction since page per_page; then
+            return 0
+        fi
+    else
+        ______x_cmd_gt_get_multi "/v5/orgs/${org##*/}/issues" filter state labels sort direction since page per_page && \
+            return 0
+    fi
+    gt_log error "Couldn't find any data by: ${org}"
+    return 1
+
 }
 
+# shellcheck disable=SC2154
 ___x_cmd_gt_enterprise_issue(){
     param:scope     "gitee/$O"
     param:dsl       '
@@ -157,13 +216,25 @@ options:
     --assignee      "assignee"                                     <>=""
     --creator       "creator"                                      <>=""
     --program       "program"                                      <>=""
+    --page          "page"                                         <>:number=1
+    --per_page      "per_page"                                     <>:number=50
 '
     param:run
-    # param form bug
-    [ -z "$enterprise" ] && gt_log error "enterprise path is empty" && return 1
-    ______x_cmd_gt_get "/v5/enterprises/${enterprise##*/}/issues" > aaa
-    ___ui_table_json "$(printf "%s" "______x_cmd_gt_get \"/v5/enterprises/${enterprise##*/}/issues\" filter state labels sort direction since page per_page schedule deadline created_at finished_at milestone assignee creator program  || return 1" )" \
-        IssueNumber=.number State=.issue_state Assigner=.assignee.name AssignerMarkName=.assignee.remark Repository=.repository.full_name Type=.issue_type Title=.title Url=.html_url && return 0
+
+    if [ -t 1 ]; then
+        if ___ui_table_json IssueNumber=.number State=.issue_state Assigner=.assignee.name AssignerMarkName=.assignee.remark \
+            Repository=.repository.full_name Type=.issue_type Title=.title Url=.html_url \
+            -- "______x_cmd_gt_get_multi" "/v5/enterprises/${enterprise##*/}/issues" filter state labels sort direction since \
+            page per_page schedule deadline created_at finished_at milestone assignee creator program; then
+            return 0
+        fi
+    else
+        ______x_cmd_gt_get_multi "/v5/enterprises/${enterprise##*/}/issues" filter state labels sort direction since \
+            page per_page schedule deadline created_at finished_at milestone assignee creator program && \
+            return 0
+    fi
+    gt_log error "Couldn't find any data by: ${enterprise}"
+    return 1
 }
 
 # Section : comment
@@ -175,11 +246,12 @@ subcmd:
     ls              "list all comment"
     create          "create a comment"
     update          "update a comment"
-    delete          "delete a comment"
+    del             "delete a comment"
 '
     param:run
     if [ -z "$PARAM_SUBCMD" ]; then
         gt_log warn "subcmd not found. show help." >&2
+        ___x_cmd_gt_issue _param_help_doc
         return 1
     fi
     "___x_cmd_gt_issue_comment_$PARAM_SUBCMD" "$@"
@@ -189,55 +261,76 @@ ___x_cmd_gt_issue_comment_ls(){
     param:scope     "gitee/$O"
     param:dsl       '
 options:
-    --owner         "owner"                 <>
-    --repo          "repo path"             <>
-    --number        "issue number"          <>
-    --since         "since"                 <>=""
-    --page          "page"                  <>=1
-    --per_page      "per_page"              <>=100
-    --order         "order(asc、desc)"      <>="asc"
+    --number        "issue number"                                                       <>
+    --repo          "Provide owner name and repo name.(default:the current user repo)"   <>:RepoName
+    --since         "since"                                                              <>=""
+    --page          "page"                                                               <>=1
+    --per_page      "per_page"                                                           <>=100
+    --order         "order(asc、desc)"                                                   <>="asc"
 '
     param:run
-    ___ui_table_json "$(printf "%s" "______x_cmd_gt_get_multi \"/v5/repos/${owner##*/}/${repo##*/}/issues/$number/comments\" since page per_page order || return 1" )" \
-        IssueNumber=.target.issue.number Title=.target.issue.title User=.user.login body=.body && return 0
+    ___x_cmd_gt_param_init_owner_repo
+
+    if [ -t 1 ]; then
+        if ___ui_table_json CommitId=.id IssueNumber=.target.issue.number Title=.target.issue.title User=.user.login Body=.body \
+            -- "______x_cmd_gt_get_multi" "/v5/repos/${owner_repo}/issues/$number/comments" since order page per_page; then
+            return 0
+        fi
+    else
+        ______x_cmd_gt_get_multi "/v5/repos/${owner_repo}/issues/$number/comments" since order page per_page && \
+            return 0
+    fi
+    gt_log error "Couldn't find any data by: ${owner_repo}"
+    return 1
 }
 
+# shellcheck disable=SC2086,SC2154
 ___x_cmd_gt_issue_comment_create(){
     param:scope     "gitee/$O"
     param:dsl       '
 options:
-    --owner         "owner"                             <>
-    --repo          "repo path"                         <>
-    --number        "issue number"                      <>
-    --body          "The contents of the comment."      <>
+    --repo          "Provide owner name and repo name.(default:the current user repo)"   <>:RepoName
+    --number        "issue number"                                                       <>
+    --body          "The contents of the comment"                                        <>
 '
     param:run
-    ______x_cmd_gt_post_json "/v5/repos/${owner##*/}/${repo##*/}/issues/$number/comments"  body
+
+    local data
+    data="$(______x_cmd_gt_post_json "/v5/repos/${owner##*/}/${repo##*/}/issues/$number/comments" body || return 1)"
+    ___x_cmd_gt_json_query_rename "$data" id=.target.issue.number title=.target.issue.title body=.body
+    [ -n "$id" ] && ___x_cmd_ui tf "true" "Success" "id: $id" "title: $title" "comment_body: $body" && return 0
+                    gt_log        "error" "Create Comment failure"                                  && return 1
 }
 
 ___x_cmd_gt_issue_comment_update(){
     param:scope     "gitee/$O"
     param:dsl       '
 options:
-    --owner         "owner"                            <>
-    --repo          "repo path"                        <>
-    --id            "comments id"                       <>
-    --body          "The contents of the comment."      <>
+    --repo          "Provide owner name and repo name.(default:the current user repo)"   <>:RepoName
+    --id            "comments id"                                                        <>
+    --body          "The contents of the comment"                                        <>
 '
     param:run
-    ______x_cmd_gt_patch_json "/v5/repos/${owner##*/}/${repo##*/}/issues/comments/${id}"  body
+
+    local data
+    data="$(______x_cmd_gt_patch_json "/v5/repos/${owner##*/}/${repo##*/}/issues/comments/${id}" body || return 1)"
+    ___x_cmd_gt_json_query_rename "$data" id=.target.issue.number title=.target.issue.title body=.body
+    [ -n "$id" ] && ___x_cmd_ui tf "true" "Success" "id: $id" "title: $title" "comment_body: $body" && return 0
+                    gt_log        "error" "Update Comment failure"                                  && return 1
 }
 
-___x_cmd_gt_issue_comment_delete(){
+# shellcheck disable=SC2181
+___x_cmd_gt_issue_comment_del(){
     param:scope     "gitee/$O"
     param:dsl       '
 options:
-    --owner         "owner"                            <>
-    --repo          "repo path"                        <>
-    --id            "comments id"                       <>
+    --repo          "Provide owner name and repo name.(default:the current user repo)"   <>:RepoName
+    --id            "comments id"                                                        <>
 '
     param:run
-    ______x_cmd_gt_delete "/v5/repos/${owner##*/}/${repo##*/}/issues/comments/${id}"
+    ______x_cmd_gt_delete "/v5/repos/${owner##*/}/${repo##*/}/issues/comments/${id}" 1>/dev/null 2>&1
+    [ $? -eq 0 ] && ___x_cmd_ui tf "true" "Deleted comment successfully"                      && return 0
+                    gt_log error "Deleting comment failure by ${owner##*/} ${repo##*/} $id."  && return 1
 }
 
 # EndSection
diff --git a/lib/repo/tag b/lib/repo/tag
--- a/lib/repo/tag
+++ b/lib/repo/tag
@@ -4,8 +4,8 @@
 ___x_cmd_gt_repo_tag(){
     param:dsl    '
 subcmd:
-    ls              "list tag"
-    add             "add tag"
+    ls              "List repo tag"
+    add             "Add repo tag"
 '
     param:run
     if [ -z "$PARAM_SUBCMD" ]; then
@@ -13,37 +13,54 @@ subcmd:
         ___x_cmd_gt_repo_tag _param_help_doc
         return 1
     fi
-    
+
     "___x_cmd_gt_repo_tag_$PARAM_SUBCMD" "$@"
 }
 
+# shellcheck disable=SC2154,SC2086
 ___x_cmd_gt_repo_tag_ls() {
     param:scope     "gitee/$O"
     param:dsl    '
 options:
-    #1|--repo          "Repo name"                 <>:repo
+    #1|--repo          "Provide owner name and repo name.(default:the current user repo)"   <>:RepoName
 '
     param:run
 
     ___x_cmd_gt_param_init_owner_repo
-    ______x_cmd_gt_get "/v5/repos/${owner_repo}/tags"   
+
+    if [ -t 1 ]; then
+        if ___ui_table_json TagName=.name Message=.message Commit=.commit.sha Time=.commit.date \
+            -- "______x_cmd_gt_get" "/v5/repos/${owner_repo}/tags"; then
+            return 0
+        fi
+    else
+        ______x_cmd_gt_get "/v5/repos/${owner_repo}/tags" && \
+            return 0
+    fi
+    gt_log error "Couldn't find any data by: $owner_repo"
+    return 1
 }
 
 
 # #1: owner/repo/master
 # #2: tag_name
 # #3: tag_message
+# shellcheck disable=SC2154,SC2181
 ___x_cmd_gt_repo_tag_add() {
     param:scope     "gitee/$O"
     param:dsl    '
 options:
-    --repo          "Repo name"                 <>:repo
-    --refs          "starting point name"       <>="master"
-    --name          "tag name"                  <>
-    --msg           "tag message"               <>=""
+    --name          "tag name"                                                           <>
+    --repo          "Provide owner name and repo name.(default:the current user repo)"   <>:RepoName
+    --refs          "starting point name"                                                <>="master"
+    --msg           "tag message"                                                        <>=""
 '
     param:run
     ___x_cmd_gt_param_init_owner_repo
+
     ______x_cmd_gt_post_json "/v5/repos/${owner_repo}/tags" \
-        refs tag_message="$msg" tag_name="$name"  
+        refs tag_message="$msg" tag_name="$name" 1>/dev/null 2>&1
+
+    [ $? -ne 0 ] && gt_log error "Add $owner_repo tag: $name failure"      &&   return 1
+                    gt_log info  "Add $owner_repo tag: $name successfully" &&   return 0
 }
