...

diff --git a/mod/pkg/lib/mutate/download b/mod/pkg/lib/mutate/download
--- a/mod/pkg/lib/mutate/download
+++ b/mod/pkg/lib/mutate/download
@@ -7,8 +7,9 @@ ___x_cmd_pkg_download(){
     x:trace pkg/download
 
     local pkg_name="${1:?Provide pkg name}"
-    local version="${2:-$(___x_cmd_pkg___default_version "$pkg_name")}"
+    local version="${2:-$(___x_cmd_pkg_default_version "$pkg_name")}"
     local osarch="${3:-${___X_CMD_PKG_OSARCH:-$(___x_cmd_pkg_osarch)}}"
+    [ -n "$version" ] || return
 
     local sb_repo
     local sb_app
@@ -19,10 +20,14 @@ ___x_cmd_pkg_download(){
     fi
 
     local url_list
-    local file_suffix
     url_list="$(___x_cmd_pkg___list "$pkg_name" "$version" "$osarch" "url.${___X_CMD_WHICHNET:-_}" )"
-    ___x_cmd_pkg___attr "$pkg_name" "$version" "$osarch" file_suffix
+    [ -n "$url_list" ] || {
+        pkg:error "Not found url."
+        return 1
+    }
 
+    local file_suffix
+    ___x_cmd_pkg___attr "$pkg_name" "$version" "$osarch" file_suffix
     local url
     local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$pkg_name/$version.$file_suffix"
     mkdir -p "$___X_CMD_PKG_DOWNLOAD_PATH/$pkg_name"
@@ -44,6 +49,7 @@ ___x_cmd_pkg_download(){
         # TODO: ___x_cmd_httpget support 302
         # ___x_cmd_httpget "$url" "$ball" || {
         pkg:info "Download $pkg_name $version from $url to $ball"
+        # TODO: x curl
         curl --progress-bar --location --retry-max-time 10 --retry 0 "$url" --output "$ball" || {
             pkg:warn "Fail to download from $url"
             continue
@@ -61,7 +67,7 @@ A
 
 ___x_cmd_pkg_download_file___from_static_build_and_deflate(){
     local IFS='
-    '
+'
     local repo="${1:?Provide repo name, like p7zip}"
     local app="${2:-${repo}}"
     local version="${3:?Provide version}"
@@ -69,18 +75,19 @@ ___x_cmd_pkg_download_file___from_static_build_and_deflate(){
     pkg:debug "Download static-build. repo: $repo app: $app"
 
     local target="$___X_CMD_PKG_INSTALL_PATH/$repo/$version"
-    mkdir -p "$target"
+    x ensuredir "$target" || return 1
 
-    local arch
-    arch="$(os arch)"
-    local osname
-    osname="$(os name)"
+    local osarch
+    osarch="${___X_CMD_PKG_OSARCH:-$(___x_cmd_pkg_osarch)}"
+    local arch="${osarch#*/}"
+    local osname="${osarch%/*}"
 
     local exe
     case "$osname" in
-        win)    exe=$app.x64.exe        ;;
-        *)      exe=$app.${osname}.${arch}  ;;
+        win)        exe=$app.${osname}.${arch}.exe          ;;
+        *)          exe=$app.${osname}.${arch}              ;;
     esac
+
     # Rely
     if [ ! -f "$target/$exe" ]; then
         pkg:info "Downloading: $repo/$app/$version/$exe.7z to $target"
@@ -106,7 +113,7 @@ ___x_cmd_pkg_download_file___from_static_build_and_deflate(){
                     local i
                     local suffix
 
-                    # TODO: using job for concurrency.
+                    # TODO: using curl shared-connection facility.
                     for i in $(seq "$size"); do
                         # suffix="$(printf "%03s" "$i")" # Not work in gnu bash
                         suffix="$(printf "%3s" "$i" | tr " " 0)"
@@ -129,25 +136,12 @@ ___x_cmd_pkg_download_file___from_static_build_and_deflate(){
 
 
 ___x_cmd_pkg_download___check_hashsum(){
-    local filepath="$1"
+    local filepath="${1:?Please priovide filepath}"
 
-    local md5="$2"
-    local sha1="$3"
-    local sha256="$4"
-    local sha512="$5"
+    [ -z "$2" ]  ||  [ "$(___x_cmd_md5       "$filepath")" = "$2" ]     ||      return 1
+    [ -z "$3" ]  ||  [ "$(___x_cmd_sha1      "$filepath")" = "$3" ]     ||      return 1
+    [ -z "$4" ]  ||  [ "$(___x_cmd_sha256    "$filepath")" = "$4" ]     ||      return 1
+    [ -z "$5" ]  ||  [ "$(___x_cmd_sha512    "$filepath")" = "$5" ]     ||      return 1
 
-    if [ -n "$sha512" ]; then
-        [ "$(___x_cmd_sha512 "$filepath")" != "$sha512" ]
-    elif [ -n "$sha256" ]; then
-        [ "$(___x_cmd_sha256 "$filepath")" != "$sha256" ]
-    elif [ -n "$sha1" ]; then
-        [ "$(___x_cmd_sha1 "$filepath")" != "$sha1" ]
-    elif [ -n "$md5" ]; then
-        [ "$(___x_cmd_md5 "$filepath")" != "$md5" ]
-    else
-        # In the future, will return 1
-        x:warn "No checksum provided."
-        return 0
-    fi
-
+    return 0
 }
diff --git a/mod/wx/lib/util b/mod/wx/lib/util
--- a/mod/wx/lib/util
+++ b/mod/wx/lib/util
@@ -1,6 +1,12 @@
+# shellcheck shell=sh disable=SC3043
 
 ___x_cmd_wx_run(){
-    local wxfile="${1:-.}"; shift
+    local wxfile="${1:-.}"; [ "$#" -eq 0 ] || shift
+
+    case "$wxfile" in
+        @me/*|@i/*|@/*|@*/*) wxfile="$(x hub file which script/demo.wx)" || return 1 ;;
+    esac
+
     local ___X_CMD_WX_UNPKG_
     if [ -d "$wxfile" ]; then
         ___X_CMD_WX_UNPKG_="$wxfile"
@@ -15,18 +21,21 @@ ___x_cmd_wx_run(){
         return 1
     fi
 
-    if [ -f ".x-cmd/run-dist" ]; then
-        x ws run-dist "$@"
-    else
-        if [ -f ".x-cmd/installed_already" ] && ! x ws installed_already; then
-            if ! x ws install; then
-                local exit=$?
-                x:error "Exit=$exit: Installation failure."
-                return "$exit"
-            fi
-        fi
-        x ws run "$@"
-    fi
+    # TODO: To use no shift at ws module.
+    x ws run run "$@"
+
+    # if [ -f ".x-cmd/run-dist" ]; then
+    #     x ws run-dist "$@"
+    # else
+    #     if [ -f ".x-cmd/installed_already" ] && ! x ws installed_already; then
+    #         if ! x ws install; then
+    #             local exit=$?
+    #             x:error "Exit=$exit: Installation failure."
+    #             return "$exit"
+    #         fi
+    #     fi
+    #     x ws run "$@"
+    # fi
 
     if ! cd "$___X_CMD_WX_RUN_OLD_PWD"; then
         x:error "Cannot return to original folder: $___X_CMD_WX_RUN_OLD_PWD"
@@ -44,15 +53,14 @@ ___x_cmd_wx_is_workspace_runnable(){
 ___x_cmd_wx_pkg(){
     local workspace="${1:-.}"
     if ! ___x_cmd_wx_is_workspace_runnable "$workspace"; then
+        x:error "Workspace is not runnable: $workspace | PWD: $PWD"
         return 1
     fi
 
-    if [ -n "$2" ]; then
-        tar cf "$2" "$workspace" --exclude "$2"
-    else
-        local name="${PWD##*/}"
-        tar cf "$name.wx" "$workspace" --exclude "*.wx"
-    fi
+    local target="${2:-${PWD##*/}.wx}"
+    local cmd="tar --exclude=$target -czf $target $workspace"
+    eval "$cmd"
+    x:debug "Created tar: $cmd"
 }
 
 ___x_cmd_wx_unpkg_(){
@@ -76,7 +84,8 @@ ___x_cmd_wx_unpkg_(){
         return 1
     fi
 
-    if ! tar xf "$wxfile" "$___X_CMD_WX_UNPKG_"; then
+    mkdir -p "$___X_CMD_WX_UNPKG_"
+    if ! tar xf "$wxfile"  --directory="$___X_CMD_WX_UNPKG_"; then
         x:error "Exit=1 for failure on delation: $wxfile"
         ___X_CMD_WX_UNPKG_=
         return 1
@@ -92,5 +101,3 @@ ___x_cmd_wx_unpkg(){
 ___x_cmd_wx_ls(){
     :
 }
-
-
