...

diff --git a/mod/pkg/lib/mutate/install b/mod/pkg/lib/mutate/install
--- a/mod/pkg/lib/mutate/install
+++ b/mod/pkg/lib/mutate/install
@@ -25,12 +25,13 @@ ___x_cmd_pkg_install(){
         . "$script_path"
         return 0
     else
-        local sb_repo
-        local sb_app
+        local sb_repo sb_app
         ___x_cmd_pkg___static_build_attr "$name" "$version" "$osarch"
         if [ -n "$sb_repo" ] && [ -n "$sb_app" ]; then
+            pkg:debug "static-build return 0"
             return 0
         fi
+
         ___x_cmd_pkg_install___unzip "$name" "$version" "$osarch" || return
     fi
 }
@@ -88,22 +89,29 @@ ___x_cmd_pkg_install___unzip(){
     bin_path="$(___x_cmd_pkg_xbin_path "$name" "$version")"
     [ ! -x "$bin_path" ] || return 0
 
-    pkg:debug "bin_path: $bin_path"
 
-    local file_suffix
-    ___x_cmd_pkg___attr "$name" "$version" "$osarch" file_suffix
+    local file_suffix unpack_way
+    ___x_cmd_pkg___attr "$name" "$version" "$osarch" "file_suffix,unpack_way"
     local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/$version.$file_suffix"
-    local unpack_dir="$___X_CMD_PKG_DOWNLOAD_PATH/$name/$version"
     local tgt="$___X_CMD_PKG_INSTALL_PATH/$name/$version"
 
-    pkg:debug "Unpack: $ball to $unpack_dir"
-    x uz "$ball" "$unpack_dir" 1>/dev/null || {
-        pkg:warn "Fail to unzip $ball"
-    }
-    x rmrf "$tgt"; mkdir -p "$tgt"
-    pkg:debug "Moving $unpack_dir to $tgt"
-    mv -f "$unpack_dir"/*/* "$tgt"
-    x rmrf "$unpack_dir"
+    pkg:debug "bin_path: $bin_path unpack_way: $unpack_way"
+
+    if [ "$unpack_way" = "unpack_copy_to_target_dir" ]; then
+        local unpack_dir="$___X_CMD_PKG_DOWNLOAD_PATH/$name/$version"
+        pkg:debug "Unpack: $ball to $unpack_dir"
+        x uz "$ball" "$unpack_dir" 1>/dev/null || {
+            pkg:warn "Fail to unzip $ball"
+        }
+        x rmrf "$tgt"; mkdir -p "$tgt"
+        pkg:debug "Moving $unpack_dir to $tgt"
+        mv -f "$unpack_dir"/*/* "$tgt"
+        x rmrf "$unpack_dir"
+    else
+        pkg:info "Unpack: $ball to $tgt"
+        x uz "$ball" "$tgt"  || {
+            pkg:warn "Fail to unzip $ball"
+        }
+    fi
     pkg:info "Finish unpack $name $version to $tgt"
 }
-
