...

diff --git a/mod/pkg/lib/download b/mod/pkg/lib/download
--- a/mod/pkg/lib/download
+++ b/mod/pkg/lib/download
@@ -4,36 +4,46 @@
 # TODO: Maybe using a P2P share connection for mirror downloading.
 
 ___x_cmd_pkg_download(){
+    x:trace pkg/download
+
     local pkg_name="${1:?Provide pkg name}"
-    local version="${2:?Provide version}"
+    local version="${2:-$(___x_cmd_pkg___default_version "$pkg_name")}"
     local osarch="${3:-${___X_CMD_PKG_OSARCH:-$(___x_cmd_pkg_osarch)}}"
+
+    local sb_repo
+    local sb_app
+    ___x_cmd_pkg___static_build_attr "$pkg_name" "$version" "$osarch"
+    if [ -n "$sb_repo" ] && [ -n "$sb_app" ]; then
+        ___x_cmd_pkg_download_file___from_static_build_and_deflate "$sb_repo" "$sb_app" "$version"
+        return
+    fi
 
     local url_list
     local file_suffix
-    url_list="$(___x_cmd_pkg___list "$@" "$osarch" "url.${___X_CMD_WHICHNET:-_}" )"
-    ___x_cmd_pkg___attr "$@" "$osarch" file_suffix
+    url_list="$(___x_cmd_pkg___list "$pkg_name" "$version" "$osarch" "url.${___X_CMD_WHICHNET:-_}" )"
+    ___x_cmd_pkg___attr "$pkg_name" "$version" "$osarch" file_suffix
 
     local url
     local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$pkg_name/$version.$file_suffix"
-    pkg:debug "Download url_list: $url_list ball: $ball"
+    mkdir -p "$___X_CMD_PKG_DOWNLOAD_PATH/$pkg_name"
+    pkg:debug "Download $pkg_name $version url_list: $url_list ball: $ball"
 
     local md5
     local sha1
     local sha256
     local sha512
 
-    ___x_cmd_pkg___attr "$@" "$osarch" "md5,sha1,sha256,sha512"
-
+    ___x_cmd_pkg___attr "$pkg_name" "$version" "$osarch" "md5,sha1,sha256,sha512"
     if [ -f "$ball" ]; then
         ! ___x_cmd_pkg_download___check_hashsum "$ball" "$md5" "$sha1" "$sha256" "$sha512" || return 0
 
         pkg:warn "File corrupted. Download the $ball again."
         x rmrf "$ball"
     fi
-
     while read -r url; do
         # TODO: ___x_cmd_httpget support 302
         # ___x_cmd_httpget "$url" "$ball" || {
+        pkg:info "Download $pkg_name $version from $url to $ball"
         curl --progress-bar --location --retry-max-time 10 --retry 0 "$url" --output "$ball" || {
             pkg:warn "Fail to download from $url"
             continue
@@ -48,6 +58,75 @@ $url_list
 A
 
 }
+
+___x_cmd_pkg_download_file___from_static_build_and_deflate(){
+    local IFS='
+    '
+    local repo="${1:?Provide repo name, like p7zip}"
+    local app="${2:-${repo}}"
+    local version="${3:?Provide version}"
+
+    pkg:debug "Download static-build. repo: $repo app: $app"
+
+    local target="$___X_CMD_PKG_INSTALL_PATH/$repo/$version"
+    mkdir -p "$target"
+
+    local arch
+    arch="$(os arch)"
+    local osname
+    osname="$(os name)"
+
+    local exe
+    case "$osname" in
+        win)    exe=$app.x64.exe        ;;
+        *)      exe=$app.${osname}.${arch}  ;;
+    esac
+    # Rely
+    if [ ! -f "$target/$exe" ]; then
+        pkg:info "Downloading: $repo/$app/$version/$exe.7z to $target"
+        if ! ___x_cmd_curl_gitx static-build "${repo}" main "$app/$version/$exe.7z" "$target/$exe.7z"; then
+            pkg:warn "Download failure: $repo/main $app/$version/$exe.7z"
+            pkg:warn "File Not Found. Perhaps the platform is NOT supported: $exe"
+            return 1
+        fi
+
+        (
+            cd "$target" && {
+                local size
+
+                size=$(wc -c "$exe.7z")
+                size=${size% *}
+                size=$(printf "%s" $size)   # Notice: Intentionary let it unquoted.
+
+                xrc p7zip
+                if [ "$size" -gt 20 ]; then
+                    p7zd x "$exe.7z" 1>/dev/null 2>/dev/null
+                else
+                    size="$(cat "$exe.7z")"
+                    local i
+                    local suffix
+
+                    # TODO: using job for concurrency.
+                    for i in $(seq "$size"); do
+                        # suffix="$(printf "%03s" "$i")" # Not work in gnu bash
+                        suffix="$(printf "%3s" "$i" | tr " " 0)"
+                        if ! ___x_cmd_curl_gitx static-build "${repo}" main "$app/$version/$exe.7z.$suffix" "$target/$exe.7z.$suffix"; then
+                            pkg:warn "Download failure in $exe.7z.$suffix" >&2
+                            return 1
+                        fi
+                    done
+
+                    pkg:info "Using p7zd to decompress: $target/$exe.7z.001"
+                    cat $target/$exe.7z.0* > $exe.7z
+                    p7zd x "$exe.7z" 1>/dev/null 2>/dev/null
+                fi && chmod +x "$exe" \
+                    && pkg:info "Finish file decompress and chmod."
+            }
+        )
+    fi && return 0
+    return 1
+}
+
 
 ___x_cmd_pkg_download___check_hashsum(){
     local filepath="$1"
