...

diff --git a/mod/gl/lib/config b/mod/gl/lib/config
--- a/mod/gl/lib/config
+++ b/mod/gl/lib/config
@@ -17,7 +17,7 @@ ___x_cmd_gl_config(){
 ___x_cmd_gl_config_which(){
     param:void
     local O="${O:-___x_cmd_gl_GL_DEFAULT}"
-    printf "%s" "$___X_CMD_ROOT/.config/x-bash/app.gitee.config/$O"
+    printf "%s" "$___X_CMD_ROOT/.config/x-bash/app.gitlab.config/$O"
 }
 
 ___x_cmd_gl_config_get(){
@@ -26,13 +26,13 @@ ___x_cmd_gl_config_get(){
 type:
     ConfigName  =   oauth_token user git_protocol
 options:
-    --host        "host name"                               <>="gitee.com"
+    --host        "host name"                               <>="gitlab.com"
     #1            "The name of the configuration to get"    <>:ConfigName
 '
     param:run
     local O="${O:-___x_cmd_gl_GL_DEFAULT}"
-    [ -e  "$___X_CMD_ROOT/.config/x-bash/app.gitee.config/$O" ] || return 1
-    ___x_cmd_git_config_get "$___X_CMD_ROOT/.config/x-bash/app.gitee.config/$O" "$host" "$1"
+    [ -e  "$___X_CMD_ROOT/.config/x-bash/app.gitlab.config/$O" ] || return 1
+    ___x_cmd_git_config_get "$___X_CMD_ROOT/.config/x-bash/app.gitlab.config/$O" "$host" "$1"
 }
 
 ___x_cmd_gl_config_set(){
@@ -41,14 +41,14 @@ ___x_cmd_gl_config_set(){
 type:
     ConfigName  =   oauth_token user git_protocol
 options:
-    --host    "host name"                             <>="gitee.com"
+    --host    "host name"                             <>="gitlab.com"
     #1        "Please provide configuration key"      <>:ConfigName
     #2        "Please provide configuration val"      <>
 '
     param:run
     local O="${O:-___x_cmd_gl_GL_DEFAULT}"
-    local ___gitee_path="$___X_CMD_ROOT/.config/x-bash/app.gitee.config/$O"
-    [ -e  "$___gitee_path" ] || mkdir -p "$___gitee_path##*/"
-    ___x_cmd_git_config_set "$___gitee_path" "$host" "$1" "$2" && return 0
-    gl_log error "gitee config set fail"
+    local ___gitlab_path="$___X_CMD_ROOT/.config/x-bash/app.gitlab.config/$O"
+    [ -e  "$___gitlab_path" ] || mkdir -p "$___gitlab_path##*/"
+    ___x_cmd_git_config_set "$___gitlab_path" "$host" "$1" "$2" && return 0
+    gl_log error "gitlab config set fail"
 }
