...

diff --git a/mod/yanfa/lib/release b/mod/yanfa/lib/release
--- a/mod/yanfa/lib/release
+++ b/mod/yanfa/lib/release
@@ -19,8 +19,12 @@ ___x_cmd_yanfa_release_add()(
     local branch="${3:-main}"
 
     cd "$___X_CMD_YANFA_RELEASE_TMP" || exit 1
+
     for ((i=1; i<=3; i=i+1)); do
-        git clone --depth=1 "$position" -b "$branch" && exit 0
+        if git clone --quiet --depth=1 "$position" -b "$branch"; then
+            x log :yanfa "<release-add> [$mod/$branch] Cloning success from $position"
+            exit 0
+        fi
         x log :yanfa warn "<release-add> Fail to git clone. Retry it after 5 seconds"
         if ! sleep 5; then
             x log :yanfa warn "<release-add> Sleep interrupted."
@@ -43,7 +47,6 @@ ___x_cmd_yanfa_release_update(){
         while read -r mod; do
             # OUT=/dev/null
             x job put "${1:-7}" ___x_cmd_yanfa_release_add "$mod"
-            printf "%s\n" "Cloning: $mod" >&2
         done
 
         x job wait
@@ -83,7 +86,6 @@ ___x_cmd_yanfa_release_lsfile()(
 ___x_cmd_yanfa_release_cpfile_inner(){
     if [ -d "$2" ]; then
         local p="$2/$1"
-        echo "$p"
         [ -d "${p%/*}" ] || mkdir -p "${p%/*}"
         cp "$1" "$p"
     else
@@ -122,9 +124,11 @@ ___x_cmd_yanfa_release_tgz()(
 
     WSROOT="$(x wsroot)"
 
+    [ -f "$scope.tgz" ] && rm "$scope.tgz"
+
     cd "$WSROOT/mod" &&
         mkdir -p "$WSROOT/dist" &&
-        tar czvf "$scope.tgz" * &&
+        tar czf "$scope.tgz" * 2>/dev/null &&
         mv "$scope.tgz" "$WSROOT/dist/$scope.tgz" &&
         ls -alh "$WSROOT/dist/$scope.tgz"
 )
@@ -148,11 +152,25 @@ ___x_cmd_yanfa_release_7z()(
 
 # EndSection
 
-___x_cmd_yanfa_release_pub(){
+___x_cmd_yanfa_release_pub()(
     param:void
-    ___x_cmd_yanfa_release_update "${CONCURRENCY:-7}" && ___x_cmd_yanfa_release_tgz "$@" && git add . && git commit -m ... && ___x_cmd_yanfa_ws_push && return 0
-    return 1
-}
+    # set -o errexit
+    if {
+        x log :yanfa warn "<release-pub> update"
+        ___x_cmd_yanfa_release_update "${CONCURRENCY:-7}"
+    } && {
+        x log :yanfa warn "<release-pub> create tgz"
+        ___x_cmd_yanfa_release_tgz "$@"
+    } && {
+        x log :yanfa warn "<release-pub> Add && Commit && Push"
+        git add . && git commit -m ... && ___x_cmd_yanfa_ws_push
+
+    }; then
+        x log :yanfa warn "<release-pub> OK"
+    else
+        x log :yanfa warn "<release-pub> Fail"
+    fi
+)
 
 ___x_cmd_yanfa_release(){
 
