...

diff --git a/mod/yanfa/lib/release b/mod/yanfa/lib/release
--- a/mod/yanfa/lib/release
+++ b/mod/yanfa/lib/release
@@ -34,37 +34,36 @@ ___x_cmd_yanfa_release(){
 }
 # EndSection
 
+___x_cmd_run_or_fail(){
+    local start_msg="${1:?Provide start msg}"
+    local fail_msg="${2:?Provide failure msg}"
+    shift 2
+
+    yanfa:debug "$start_msg"
+    "$@"
+    local code=$?
+    if [ "$code" -eq 0 ]; then
+        yanfa:debug "Exit=$code. Success"
+    else
+        yanfa:debug "Exit=$code: $fail_msg"
+    fi
+    return "$code"
+}
+
 # Section: pub
 ___x_cmd_yanfa_release_pub()(
     param:void
     x:trace yanfa/relesae/pub
     # set -o errexit
-    if {
-        yanfa:info "update"
-        ___x_cmd_yanfa_release_update "${CONCURRENCY:-7}" || {
-            local code=$?;  yanfa:info "update fail exit: $?"
-            false
-        }
-    } && {
-        yanfa:info "create tgz"
-        ___x_cmd_yanfa_release_tgz "$@" || {
-            local code=$?;  yanfa:info "create tgz exit: $code"
-            false
-        }
-    } && {
-        if [ -n "$NO_UPLOAD" ]; then
-            yanfa:info "No Upload. Skip Add && Commit && Push"
-        else
-            yanfa:info "Add && Commit && Push"
-            if ! git add . && git commit -m ... && ___x_cmd_yanfa_ws_push; then
-                local code=$?;  yanfa:info "Add && Commit && Push exit: $code"
-                false
-            fi
-        fi
-    }; then
+    if  ___x_cmd_run_or_fail "Start update"             "Update fail."              ___x_cmd_yanfa_release_update   "${CONCURRENCY:-7}" && \
+        ___x_cmd_run_or_fail "Start CPFILE"             "CPFILE fail."              ___x_cmd_yanfa_release_cpfile   "${CONCURRENCY:-7}" && \
+        ___x_cmd_run_or_fail "Start Generate Meta"      "Generate Meta fail."       ___x_cmd_yanfa_release_meta     "${CONCURRENCY:-7}" && \
+        ___x_cmd_run_or_fail "Start tgz"                "tgz fail."                 ___x_cmd_yanfa_release_tgz                          && \
+        ___x_cmd_yanfa_upload ;
+    then
         yanfa:info "OK"
     else
-        yanfa:info "Fail"
+        yanfa:error "Fail"
         return 1
     fi
 )
@@ -72,7 +71,7 @@ ___x_cmd_yanfa_release_pub()(
 
 # Section: module add pull update
 
-___X_CMD_YANFA_RELEASE_TMP="${TMPDIR}/release/mod"
+___X_CMD_YANFA_RELEASE_TMP="${TMPDIR%/}/release/mod"
 
 ___x_cmd_yanfa_release_add()(
     x:trace yanfa/relesae/add "[name=$1]" "[position=$2]" "[branch=$branch]"
@@ -83,8 +82,7 @@ ___x_cmd_yanfa_release_add()(
 
     cd "$___X_CMD_YANFA_RELEASE_TMP" || exit 1
 
-    local i
-    i=1
+    local i=1
     while [ "$i" -le "${RETRY:-3}" ]; do
         if git clone --quiet --depth=1 "$position" -b "$branch"; then
             yanfa:info "[$mod/$branch] Cloning success from $position"
@@ -102,34 +100,21 @@ ___x_cmd_yanfa_release_add()(
 
 ___x_cmd_yanfa_release_update(){
     param:void
-    x:trace yanfa/relesae/update "[concurrency=$1]"
 
-    local IFS=""
-    local mod
+    x:trace yanfa/relesae/update
 
-    rm -rf "$___X_CMD_YANFA_RELEASE_TMP" # TODO: x rmrf
-    mkdir -p "$___X_CMD_YANFA_RELEASE_TMP"
+    local ___X_CMD_YANFA_CONCURRENCY="${1:-$___X_CMD_YANFA_CONCURRENCY}"
+    local IFS=" "; yanfa:info "[concurrency=$___X_CMD_YANFA_CONCURRENCY]: $*"
 
+    x rmrf "$___X_CMD_YANFA_RELEASE_TMP"
+    x mkdirp "$___X_CMD_YANFA_RELEASE_TMP"
+
+    local ___X_CMD_JOB_WRAPPER=log # report
     ___x_cmd_yanfa_release_lsmod | {
-        while read -r mod; do
-            # OUT=/dev/null
+        local mod; while read -r mod; do
             x job put "${1:-7}" ___x_cmd_yanfa_release_add "$mod"
         done
-
-        x job wait
-    } | while read -r line; do
-        printf "%s\n" "$line"
-        case "$line" in
-            Write*)
-                printf "%s\n" "---------------"
-                cat "${line#Write: }"
-                printf "%s\n" "---------------"
-        esac
-    done
-
-    yanfa:debug "Starting CPFILE"
-    ___x_cmd_yanfa_release_cpfile
-    local code=$?; yanfa:debug "FINISIH CPFILE exit: $code"
+    } | cat # x job report
 }
 
 # EndSection
@@ -142,7 +127,7 @@ ___x_cmd_yanfa_release_lsmod(){
     x:trace yanfa/relesae/lsmod "$@"
     ___x_cmd_yanfa_mod_ls "$@"
     local code=$?
-    yanfa:info "___x_cmd_yanfa_release_lsmod: $code"
+    yanfa:debug "___x_cmd_yanfa_release_lsmod: $code"
     return $code
 }
 
@@ -173,53 +158,54 @@ ___x_cmd_yanfa_release_cpfile_inner(){
     # x:trace yanfa/relesae/cpfile/inner        # Use debug
     if [ -d "$2" ]; then
         local p="$2/$1"
-        [ -d "${p%/*}" ] || mkdir -p "${p%/*}"
-        if ! cp "$1" "$p"; then
-            yanfa:info fail to cp [src=$1] to [dst=$p]
+        if ! x cp "$1" "$p"; then
+            yanfa:info "fail to cp [src=$1] to [dst=$p]"
         fi
     else
-        if ! cp "$1" "$2"; then
-            yanfa:info fail to cp [src=$1] to [dst=$2]
+        if ! x cp "$1" "$2"; then
+            yanfa:info "fail to cp [src=$1] to [dst=$2]"
         fi
     fi
 }
 
-___x_cmd_yanfa_release_cpfile()(
+___x_cmd_yanfa_release_cpfile(){
     x:trace yanfa/relesae/cpfile
-    yanfa:debug "Staring"
     local tgt
     tgt="$(x wsroot)/mod"
-    [ -d "$tgt" ] && rm -rf "$tgt"
-    mkdir -p "$tgt"
+    yanfa:debug "Staring cpfile: tgt=$tgt"
 
-    x rmrf "$tgt/repo.txt"
-    (
-        ___x_cmd_yanfa_release_lsmod |
-            while read -r mod; do
-                (
-                    cd "$___X_CMD_YANFA_RELEASE_TMP/$mod"
-                    printf "%s\t" "$mod"
-                    git rev-parse head
-                )
-        done >>"$tgt/repo.txt"
+    x rmrf "$tgt"; x mkdirp "$tgt"
+
+    ___x_cmd_yanfa_release_lsfile | (
+        cd "$___X_CMD_YANFA_RELEASE_TMP"
+        while read -r line; do
+            ___x_cmd_yanfa_release_cpfile_inner "$line" "${tgt}"
+            local code=$?; yanfa:debug "<release_cpfile> $line => $tgt: $code"
+        done
     )
+    # TODO: In Github Action, it return 1. Resulting in breaking. cpfile_inner is OK. The bug might be in while pipe.
+    yanfa:debug "exit: $?"
+}
 
-    (
+___x_cmd_yanfa_release_meta(){
+    local tgt
+    tgt="$(x wsroot)/mod"
+
+    local mod
+    ___x_cmd_yanfa_release_lsmod | while read -r mod; do
+        (
+            cd "$___X_CMD_YANFA_RELEASE_TMP/$mod"
+            printf "%s\t" "$mod"
+            git rev-parse head
+        )
+    done >"$tgt/repo.txt"
+
+    {
         printf "md5:%s\n" "$(x md5 "$tgt/repo.txt")"
         printf "sha256:%s\n" "$(x sha256 "$tgt/repo.txt")"
         printf "sha512:%s\n" "$(x sha512 "$tgt/repo.txt")"
-    ) >"$tgt/hashsum.txt"
-
-    ___x_cmd_yanfa_release_lsfile | while read -r line; do
-        (
-            cd "$___X_CMD_YANFA_RELEASE_TMP"
-            ___x_cmd_yanfa_release_cpfile_inner "$line" "$tgt"
-            yanfa:debug "<release_cpfile> $line => $tgt: $?"
-        )
-    done
-    # TODO: In Github Action, it return 1. Resulting in breaking. cpfile_inner is OK. The bug might be in while pipe.
-    yanfa:debug "exit: $?"
-)
+    } >"$tgt/hashsum.txt"
+}
 
 ___x_cmd_yanfa_release_wc(){
     param:void
@@ -230,8 +216,7 @@ ___x_cmd_yanfa_release_wc(){
 
 # EndSection
 
-# Section: tgz tar 7z
-
+# Section: tgz
 ___x_cmd_yanfa_release_tgz()(
     param:void
     case "${1:-all}" in
@@ -240,32 +225,42 @@ ___x_cmd_yanfa_release_tgz()(
         *)          return 1 ;;
     esac
 
+    local WSROOT
     WSROOT="$(x wsroot)"
 
-    [ -f "$scope.tgz" ] && rm "$scope.tgz"
+    x rmrf "$scope.tgz"
+    local code=$?
+    if [ "$code" = 0 ]; then        yanfa:debug "Cleaning up success[Exit=$code]: $scope.tgz"
+    else                            yanfa:warn  "Cleaning up Fail[Exit=$code]: $scope.tgz"
+    fi
 
     cd "$WSROOT/mod" &&
-        mkdir -p "$WSROOT/dist" &&
-        tar czf "$scope.tgz" * 2>/dev/null &&
-        mv "$scope.tgz" "$WSROOT/dist/$scope.tgz" &&
+        x z "$scope.tgz" . 2>/dev/null &&
+        x mv "$scope.tgz" "$WSROOT/dist/$scope.tgz"
+
+    local code="$?"
+    if [ "$code" = 0 ]; then
         ls -alh "$WSROOT/dist/$scope.tgz"
+    else
+        yanfa:error "Failure at yanfa zip and mv"
+        return "$code"
+    fi
 )
-
-___x_cmd_yanfa_release_7z()(
-    param:void
-    case "${1:-all}" in
-        core)       scope=core ;;
-        all)        scope=all ;;
-        *)          return 1 ;;
-    esac
-
-    WSROOT="$(x wsroot)"
-
-    cd "$WSROOT/mod" &&
-        mkdir -p "$WSROOT/dist" &&
-        7z a "$scope.7z" * &&
-        mv "$scope.7z" "$WSROOT/dist/$scope.7z" &&
-        ls -alh "$WSROOT/dist/$scope.7z"
-)
-
 # EndSection
+
+___x_cmd_yanfa_upload(){
+    local id=2
+    x ui select id "Do you want to commit and push?" "Yes" "No"
+
+    if [ "$id" = 2 ]; then
+        yanfa:info "No Upload. Skip Add && Commit && Push"
+    else
+        yanfa:info "Add && Commit && Push"
+        git add . && git commit -m ... && ___x_cmd_yanfa_ws_push;
+        local code=$?
+        if [ "$code" = 0 ]; then            yanfa:info "Success"
+        else                                yanfa:error "Add && Commit && Push exit: $code"
+        fi
+        return "$code"
+    fi
+}
