...

diff --git a/mod/advise/lib/util b/mod/advise/lib/util
--- a/mod/advise/lib/util
+++ b/mod/advise/lib/util
@@ -37,7 +37,7 @@ ___advise_main(){
     local tmp_filepath
     tmp_filepath=${advise_json_dir}/$func
 
-    [ ! -d "$advise_json_dir" ] && mkdir -p "$advise_json_dir"
+    x mkdirp "$advise_json_dir"
 
     if [ "-" = "$filepath" ]; then
         filepath=$tmp_filepath
@@ -47,14 +47,14 @@ ___advise_main(){
         local filepath=$tmp_filepath
         if [ ! -f "$filepath" ]; then
             local content
-            x:debug "Start gen advise for $func"
+            advise:debug "Start gen advise for $func"
             content="$(___X_CMD_META_MODE=1 X_CMD_ADVISE_FUNC_NAME=$func "$func" _x_cmd_advise_json)"
-            if [ $? -eq 0 ]; then
-                printf "%s" "$content" >"$filepath"
-                x:debug "Finished gen advise for $func"
-            else
-                x:error "$func: Failed gen advise json, you should define _x_cmd_advise_json subcmd or use param"
+            if [ ! $? -eq 0 ]; then
+                advise:error "___advise_main $*: Failed gen advise json"
+                return 1
             fi
+            printf "%s" "$content" >"$filepath"
+            advise:debug "Finished gen advise for $func"
         fi
     else
         cp "$filepath" "$tmp_filepath"
diff --git a/mod/yanfa/lib/mod b/mod/yanfa/lib/mod
--- a/mod/yanfa/lib/mod
+++ b/mod/yanfa/lib/mod
@@ -232,6 +232,21 @@ ___x_cmd_yanfa_mod_ls(){
 
 # EndSection
 
+___x_cmd_yanfa_mod_build()(
+    x cd "$(x wsroot)" || return 1
+    local name; name=$(___x_cmd_yanfa_ws_name); name="${name#*/}"
+    . ./latest
+    local main_func
+    main_func="$(___x_cmd_ldict_get ___X_CMD_XRC_SET_MAIN_DICT "$(xrc which "$name")")"
+    local content
+    if ! content="$(X_CMD_ADVISE_FUNC_NAME="$main_func" "$main_func" _x_cmd_advise_json)"; then
+        x log :yanfa "Fail generate $name advise.t.json"
+        return
+    fi
+    printf "%s" "$content" | x ja t > "$(x wsroot)/advise.t.json"
+    x log :yanfa "Success generate $name advise.t.json"
+)
+
 ___x_cmd_yanfa_mod(){
     if [ -f "$(x wsroot)/.x-cmd/$1" ]; then
         x ws execfile "$@"
@@ -251,6 +266,7 @@ ___x_cmd_yanfa_mod(){
     param:subcmd ___x_cmd_yanfa_mod                         \
         ls          "ls mod"                                \
         wc          "wc"                                    \
+        build       "advise_t_json"                         \
         devi        "container"                             \
         tgz         "package"                               \
         test        "test"                                  \
