...

diff --git a/mod/hub/lib/account/registration b/mod/hub/lib/account/registration
--- a/mod/hub/lib/account/registration
+++ b/mod/hub/lib/account/registration
@@ -1,6 +1,6 @@
 # shellcheck shell=sh disable=SC3043
 
-___x_cmd_hub_register_official_site(){
+___x_cmd_hub_register_telegram(){
 
     local username="${1}"
     if [ -z "$username" ]; then
@@ -8,17 +8,11 @@ ___x_cmd_hub_register_official_site(){
         read -r username
     fi
 
-    # if [ -n "$(___x_cmd_hub_token)" ]; then
-    #     # TODO: ask
-    #     printf "Detect token in this folder. Erase the token in the disk?" >&2
-    #     ___x_cmd_hub_token ""
-    # fi
-
     local token_to_activate
     token_to_activate="$(___x_cmd_hub_token_generate)"
 
-    ___x_cmd_http_browse "$___X_CMD_HUB_SERVICE_URL/xlogin?token_to_activate=${token_to_activate}&username=${username}"
-    printf "Please register to hub.x-cmd.com, then press [Enter] to continue: "
+    ___x_cmd_hub_qrcode "https://hub.x-cmd.com/t/$token_to_activate/$username"
+    printf "Please scan the QR code above, then press [Enter] to continue: "
     read -r _
 
     local userinfo
@@ -41,6 +35,36 @@ ___x_cmd_hub_register_weixin(){
     token_to_activate="$(___x_cmd_hub_token_generate)"
     ___x_cmd_hub_qrcode "$(___x_cmd_hub_wechat_register_url "${token_to_activate}" "$username")"
     printf "%s" "Please scan the QR code above, then press [Enter] to continue: "
+    read -r _
+
+    local userinfo
+    if userinfo="$(___x_cmd_hub_get_userinfo_by_token "${token_to_activate}")" ; then
+        ___x_cmd_hub_token "${token_to_activate}"
+        hub:info "Register Successfully, ${userinfo}, save token to ${___X_CMD_HUB_ENV}/.token"
+    else
+        hub:error "Register Failed"
+    fi
+}
+
+___x_cmd_hub_register_official_site(){
+
+    local username="${1}"
+    if [ -z "$username" ]; then
+        printf "%s" "Username: "
+        read -r username
+    fi
+
+    # if [ -n "$(___x_cmd_hub_token)" ]; then
+    #     # TODO: ask
+    #     printf "Detect token in this folder. Erase the token in the disk?" >&2
+    #     ___x_cmd_hub_token ""
+    # fi
+
+    local token_to_activate
+    token_to_activate="$(___x_cmd_hub_token_generate)"
+
+    ___x_cmd_http_browse "$___X_CMD_HUB_SERVICE_URL/xlogin?token_to_activate=${token_to_activate}&username=${username}"
+    printf "Please register to hub.x-cmd.com, then press [Enter] to continue: "
     read -r _
 
     local userinfo
