...

diff --git a/mod/gt/lib/issue b/mod/gt/lib/issue
--- a/mod/gt/lib/issue
+++ b/mod/gt/lib/issue
@@ -16,8 +16,8 @@ ___x_cmd_gt_issue(){
     param:subcmd:try
     param:run
 
-    gt_log warn "Subcmd Not Found."
     ___x_cmd_gt_issue _param_help_doc
+    gt_log warn "Subcmd Not Found."
     return 1
 }
 
@@ -264,8 +264,8 @@ ___x_cmd_gt_issue_comment(){
     param:subcmd:try
     param:run
     if [ -z "$PARAM_SUBCMD" ]; then
-        gt_log warn "subcmd not found. show help." >&2
         ___x_cmd_gt_issue _param_help_doc
+        gt_log warn "subcmd not found. show help." >&2
         return 1
     fi
     "___x_cmd_gt_issue_comment_$PARAM_SUBCMD" "$@"
diff --git a/mod/hub/lib/file b/mod/hub/lib/file
--- a/mod/hub/lib/file
+++ b/mod/hub/lib/file
@@ -22,39 +22,32 @@ ___x_cmd_hub_file_normalize_respath(){
 
 # Section(list): ls、 la
 
-___x_cmd_hub_file_ls(){
+___x_cmd_hub_file_list(){
     local respath="${1:-@me/}"
+    local type="${2:-""}"
+    local recursive="${3:-""}"
     respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
 
     local res
-    if ! res="$(___x_cmd_hub_client_file_ls "$respath")" ; then
+    if ! res="$(___x_cmd_hub_client_file_ls "$respath" "$type" "$recursive")" ; then
         hub:error "Failed to ls file: $res"
         return 1
     fi
     hub:debug "response: ${res}"
 
-    # TODO: Use jo or ja
-    local code
-    code="$(xrc cat awk/lib/default.awk awk/lib/json.awk awk/lib/jiter.awk )"
-    printf "%s" "$res" | awk "$code"'
-        { jiget_after_tokenize_unquote($0, ".") }'
-}
-
-___x_cmd_hub_file_la(){
-    local respath="${1:-@me/}"
-    respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
-
-    local res
-    if ! res="$(___x_cmd_hub_client_file_la "$respath")" ; then
-        hub:error "Failed to ls file: $res"
-        return 1
-    fi
-
-    if [ -t 1 ]; then
-        x ui table json PATH=.path IS_PUBLIC=.isPublic \
-            -- 'printf "%s" "$res"'
+    if [ -z "$type" ] ; then
+        # TODO: Use jo or ja
+        local code
+        code="$(xrc cat awk/lib/default.awk awk/lib/json.awk awk/lib/jiter.awk )"
+        printf "%s" "$res" | awk "$code"'
+            { jiget_after_tokenize_unquote($0, ".") }'
     else
-        printf "%s" "$res" #| x ja '(k() ~ "_id|filePath|userId|isPublic") { print v(); }'
+        if [ -t 1 ]; then
+            x ui table json PATH=.path IS_PUBLIC=.isPublic SIZE=.size MD5=.md5 CREATE_AT=.createdAt UPDATE_AT=.updateAt \
+                -- 'printf "%s" "$res"'
+        else
+            printf "%s" "$res"
+        fi
     fi
 }
 
@@ -114,36 +107,15 @@ ___x_cmd_hub_file_upload_dist(){
     }
 
     respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
-    ___x_cmd_hub_client_file_upload ___x_cmd_hub_tmp.wx "$respath"
+
+    if ! res=$(___x_cmd_hub_client_file_upload ___x_cmd_hub_tmp.wx "$respath"); then
+        hub:error "Failed: $res. Please check the respath."
+        rm -rf ___x_cmd_hub_tmp.wx
+        return 1
+    fi
+
+    printf "%s\n" "$res"
     rm -rf ___x_cmd_hub_tmp.wx
-}
-
-# EndSection
-
-# Section(share): share, private
-
-___x_cmd_hub_file_share(){
-    local respath="${1:?Please provide path}"
-    respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
-
-    if ! res="$(___x_cmd_hub_client_file_share "${respath}")" ; then
-        hub:error "Failed to share file: $res"
-        return 1
-    fi
-
-    hub:info "File shared successfully: $res"
-}
-
-___x_cmd_hub_file_private(){
-    local respath="${1:?Please provide path}"
-    respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
-
-    if ! res="$(___x_cmd_hub_client_file_private "${respath}")" ; then
-        hub:error "Failed to private file: $res"
-        return 1
-    fi
-
-    hub:info "File private successfully: $res"
 }
 
 # EndSection
diff --git a/mod/zuz/latest b/mod/zuz/latest
--- a/mod/zuz/latest
+++ b/mod/zuz/latest
@@ -1,58 +1,37 @@
-# shellcheck shell=sh disable=SC3043 # xrc
+# Author:       Li Junhao                   l@x-cmd.com
+# shellcheck    shell=sh disable=SC3043     # xrc
 
-# shellcheck shell=sh
-# author:       Li Junhao           l@x-cmd.com
-
+x log init zuz
+xrc:mod:lib zuz     cat ls z uz
 # Section: main
-
-# TODO: Use Param Generator SYMPOSIS
-xrc param/latest
 ___x_cmd_zuz(){
-    param:dsl <<A
-subcommand:
-    z|compress          "compress file"
-    uz|decompress       "decompress zipfile"
-    uzr                 "decompress zipfile then remove the original file"
-    ls                  "list compress inside file"
-A
-    param:run
-    if [ -z "$PARAM_SUBCMD" ] || [ -z "$*" ]; then
-        printf "\n%s\n    %s\n    %s\n    %s\n    %s\n" \
-                "SYMPOSIS:" \
-                "x z   <zipfile> <source...>" \
-                "x uz  <zipfile>" \
-                "x uzr <zipfile>" \
-                "x zl  <zipfile>"
-        ___x_cmd_zuz help
-        return 0
-    fi
-
-    eval "___x_cmd_zuz_$PARAM_SUBCMD" "$@"
+    case "$1" in
+        z|compress)             shift; ___x_cmd_zuz_z      "$@" ;;
+        uz|decompress)          shift; ___x_cmd_zuz_uz     "$@" ;;
+        uzr)                    shift; ___x_cmd_zuz_uzr    "$@" ;;
+        ls)                     shift; ___x_cmd_zuz_ls     "$@" ;;
+        help|-h|--help)         shift; ___x_cmd_zuz_help   "$@" ;;
+        _x_cmd_advise_json)     cat "$___X_CMD_ROOT_MOD/zuz/lib/zuz.advise.json" >&2 ;;
+        *)                      ___x_cmd_zuz_help; zuz:error "subcommand Not found." ;;
+    esac
 }
 
-# EndSection
+___x_cmd_zuz_help(){ cat "$___X_CMD_ROOT_MOD/zuz/lib/help.txt" >&2 ;}
+## EndSection
 
 # Section: other
 # NOTICE: tar czf - "$@" | split -b "$size" -a 3 - "$target_file."
 # NOTICE: In some environments, split doesnot have -d option. Thus we are using 7zip to compress
-
-x log init zuz
 ___x_cmd_zuz_run(){
     local IFS=' '
     # shellcheck disable=SC2154
-    zuz_log info "Command to execute => $* $logger_msg"
-    IFS=
-    eval "$@"
-    local exit_code="$?"
-    if [ "$exit_code" != 0 ];then
-        zuz_log debug "$*;Error Code: $exit_code"
-        return $exit_code
-    else
-        return 0
-    fi
-
+    zuz:info "Command to execute => $* $extra_logger_msg"
+    # IFS=
+    "$@"
+    local exit_code=$?
+    [ "$exit_code" = 0 ] || zuz:error "EXIT=$exit_code: $*"
+    return $exit_code
 }
-# EndSection
+## EndSection
 
-xrc zuz/lib/cat zuz/lib/ls zuz/lib/uz zuz/lib/z
 xrc setmain ___x_cmd_zuz
